// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
//  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTV2LUd7Ly5vK32IUestuT_yPYrKyetME',
    appId: '1:325274878851:web:4c3d558af78ec36fe26cb6',
    messagingSenderId: '325274878851',
    projectId: 'my-travel-10035',
    authDomain: 'my-travel-10035.firebaseapp.com',
    storageBucket: 'my-travel-10035.firebasestorage.app',
    measurementId: 'G-JX4FEYNEDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByUyVn0sowhF_IDKVbX5WsMqRCx8bVEqo',
    appId: '1:325274878851:android:e2868b4a2045e97ee26cb6',
    messagingSenderId: '325274878851',
    projectId: 'my-travel-10035',
    storageBucket: 'my-travel-10035.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Vv_kbVSV5Nr7D2LaiWy1Lyc_QbtzHls',
    appId: '1:325274878851:ios:1cff15c9a3429ba8e26cb6',
    messagingSenderId: '325274878851',
    projectId: 'my-travel-10035',
    storageBucket: 'my-travel-10035.firebasestorage.app',
    iosClientId:
        '325274878851-up0sea69r7fh4jhq1154midanpncfvrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.r08fullmovieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Vv_kbVSV5Nr7D2LaiWy1Lyc_QbtzHls',
    appId: '1:325274878851:ios:1cff15c9a3429ba8e26cb6',
    messagingSenderId: '325274878851',
    projectId: 'my-travel-10035',
    storageBucket: 'my-travel-10035.firebasestorage.app',
    iosClientId:
        '325274878851-up0sea69r7fh4jhq1154midanpncfvrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.r08fullmovieapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTV2LUd7Ly5vK32IUestuT_yPYrKyetME',
    appId: '1:325274878851:web:906cf0d5be520093e26cb6',
    messagingSenderId: '325274878851',
    projectId: 'my-travel-10035',
    authDomain: 'my-travel-10035.firebaseapp.com',
    storageBucket: 'my-travel-10035.firebasestorage.app',
    measurementId: 'G-1401B0Z42T',
  );
}
